require 'fileutils'

module CocoapodsRnrepo
  # Generates the per-pod SwiftPM package that fetches the prebuilt xcframework.
  #
  # Instead of downloading xcframeworks during `pod install`, RNRepo generates a
  # tiny SwiftPM package per pod whose single target is a remote
  # `.binaryTarget(url:checksum:)`. At build time `swift package resolve` makes
  # SwiftPM download, checksum-verify, and cache the artifact, which the build
  # phase then drops into the pod's `.rnrepo-cache/Current/<Pod>.xcframework`
  # (the path CocoaPods vendors). The app links a precompiled, SwiftPM-fetched
  # framework while still building under CocoaPods.
  #
  # One package is generated per configuration (Debug/Release) because a binary
  # target binds to a single artifact + checksum; the build phase picks the
  # directory matching the active configuration.
  class SpmPackage
    SWIFT_TOOLS_VERSION = '5.9'.freeze

    # Layout under <package_root>/.rnrepo-cache:
    #   spm/Debug/Package.swift
    #   spm/Release/Package.swift
    #   Current/<Pod>.xcframework   (stub at install time, real at build time)
    def self.spm_root(cache_dir)
      File.join(cache_dir, 'spm')
    end

    # Writes Package.swift files for the configurations present in `configs`.
    # `configs` maps a configuration name ("Debug"/"Release") to a hash with
    # :url and :checksum. The xcframework's SwiftPM target is named `target_name`.
    def self.generate(cache_dir, target_name, configs)
      configs.each do |config_name, artifact|
        next unless artifact && artifact[:url] && artifact[:checksum]

        package_dir = File.join(spm_root(cache_dir), config_name)
        FileUtils.mkdir_p(package_dir)
        File.write(File.join(package_dir, 'Package.swift'),
                   package_swift(target_name, artifact[:url], artifact[:checksum]))
      end
    end

    def self.package_swift(target_name, url, checksum)
      <<~SWIFT
        // swift-tools-version:#{SWIFT_TOOLS_VERSION}
        // Generated by @rnrepo/build-tools — do not edit.
        import PackageDescription

        let package = Package(
          name: "#{target_name}",
          products: [
            .library(name: "#{target_name}", targets: ["#{target_name}"]),
          ],
          targets: [
            .binaryTarget(
              name: "#{target_name}",
              url: "#{url}",
              checksum: "#{checksum}"
            ),
          ]
        )
      SWIFT
    end

    # Build-phase script for a single prebuilt pod. Runs before
    # "[CP] Copy XCFrameworks", selects the configuration, lets SwiftPM fetch the
    # xcframework, and stages it into Current/. A content hash gates the work so
    # repeat builds with an unchanged Package.swift skip resolving entirely.
    def self.build_phase_script(target_name)
      <<~SCRIPT
        set -e

        CACHE_DIR="${PODS_TARGET_SRCROOT}/.rnrepo-cache"
        SPM_DIR="${CACHE_DIR}/spm"
        CURRENT="${CACHE_DIR}/Current"
        TARGET_NAME="#{target_name}"

        # Select Debug vs Release by the DEBUG=1 preprocessor define rather than
        # the $CONFIGURATION name, which projects can customize ("Staging", etc.).
        CONFIG="Release"
        if echo "$GCC_PREPROCESSOR_DEFINITIONS" | grep -q "DEBUG=1"; then
          CONFIG="Debug"
        fi

        PKG_DIR="${SPM_DIR}/${CONFIG}"
        if [ ! -f "${PKG_DIR}/Package.swift" ]; then
          # Fall back to whichever configuration was generated.
          PKG_DIR="${SPM_DIR}/Release"
          [ -f "${PKG_DIR}/Package.swift" ] || PKG_DIR="${SPM_DIR}/Debug"
        fi
        if [ ! -f "${PKG_DIR}/Package.swift" ]; then
          echo "RNREPO: error: no generated SwiftPM package for ${TARGET_NAME}" >&2
          exit 1
        fi

        echo "RNREPO: ${TARGET_NAME} → fetching ${CONFIG} xcframework via SwiftPM"

        # Skip when the staged framework already matches this Package.swift.
        NEW_HASH="$(shasum -a 256 "${PKG_DIR}/Package.swift" | cut -d' ' -f1)"
        HASH_FILE="${CURRENT}/.rnrepo-build-hash"
        DEST="${CURRENT}/${TARGET_NAME}.xcframework"
        if [ -f "${HASH_FILE}" ] && [ -d "${DEST}" ] && [ "$(cat "${HASH_FILE}")" = "${NEW_HASH}" ]; then
          echo "RNREPO: ${TARGET_NAME} xcframework up to date, skipping"
          exit 0
        fi

        # Resolve dependencies so SwiftPM downloads + checksum-verifies the
        # binary artifact. `swift build` is a fallback for toolchains that defer
        # binary-artifact downloads past resolution.
        #
        # SwiftPM always compiles the manifest for the macOS host, but inside an
        # Xcode build phase SDKROOT (and friends) point at the iPhoneSimulator
        # SDK. That mismatch makes swiftc fail with "unable to load standard
        # library for target arm64-apple-macosx…" → "Invalid manifest". Clear
        # the iOS SDK environment so SwiftPM uses the macOS host toolchain.
        env -u SDKROOT -u PLATFORM_NAME -u SWIFT_PLATFORM_TARGET_PREFIX \
          swift package resolve --package-path "${PKG_DIR}" || \
          env -u SDKROOT -u PLATFORM_NAME -u SWIFT_PLATFORM_TARGET_PREFIX \
          swift build --package-path "${PKG_DIR}" >/dev/null 2>&1 || true

        XCFRAMEWORK="$(find "${PKG_DIR}/.build/artifacts" -type d -name '*.xcframework' 2>/dev/null | head -n 1)"
        if [ -z "${XCFRAMEWORK}" ]; then
          echo "RNREPO: error: SwiftPM did not produce an xcframework for ${TARGET_NAME}." >&2
          echo "        Check network access and that the artifact + checksum are published." >&2
          exit 1
        fi

        # Swap only the xcframework inside Current/ (don't wipe Current — it also
        # holds dummy.h, which the pod compiles as its source file during this
        # same build). Stage beside the destination, then move into place. Rename
        # the bundle to the vendored name so it matches the podspec's
        # vendored_frameworks path regardless of the artifact's internal naming.
        mkdir -p "${CURRENT}"
        STAGING="${DEST}.new"
        rm -rf "${STAGING}"
        cp -a "${XCFRAMEWORK}" "${STAGING}"
        rm -rf "${DEST}"
        mv "${STAGING}" "${DEST}"
        echo "${NEW_HASH}" > "${HASH_FILE}"

        # Ensure the dummy header the pod lists in source_files exists.
        [ -f "${CURRENT}/dummy.h" ] || echo "// rnrepo dummy header" > "${CURRENT}/dummy.h"

        echo "RNREPO: staged ${TARGET_NAME}.xcframework (${CONFIG})"
      SCRIPT
    end
  end
end
