name: Setup React Native Example App
description: Creates a React Native CLI app, installs dependencies, and integrates @rnrepo/build-tools

inputs:
  example_app:
    description: 'Name of the RN app directory to create'
    required: true
  rn_version:
    description: 'React Native version used in `@react-native-community/cli@latest init --version <rn_version>`'
    required: false
    default: '0.85.0'
  disable_rnrepo:
    description: 'Disable rnrepo plugin'
    required: false
    default: 'false'
  libraries:
    description: 'libraries with versions to install, format: libraryName1@version1<space>libraryName2@version2'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: ♻️ Cache bun packages
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: bun-${{ runner.os }}-rn-${{ inputs.rn_version }}-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          bun-${{ runner.os }}-rn-${{ inputs.rn_version }}-
          bun-${{ runner.os }}-

    - name: 🏗 Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: 📦 Install monorepo dependencies
      shell: bash
      run: bun install --ignore-scripts

    - name: 🏗 Create React Native App
      shell: bash
      run: bunx @react-native-community/cli@latest init ${INPUTS_EXAMPLE_APP} --version ${INPUTS_RN_VERSION} --skip-install
      env:
        INPUTS_EXAMPLE_APP: ${{ inputs.example_app }}
        INPUTS_RN_VERSION: ${{ inputs.rn_version }}

    - name: 📦 Install app dependencies
      shell: bash
      run: bun install --ignore-scripts
      working-directory: ${{ inputs.example_app }}

    - name: 📦 Install additional libraries
      if: ${{ inputs.libraries }}
      shell: bash
      run: bun add ${INPUTS_LIBRARIES}
      working-directory: ${{ inputs.example_app }}
      env:
        INPUTS_LIBRARIES: ${{ inputs.libraries }}

    - name: 📦 Install @rnrepo/build-tools
      shell: bash
      run: bun add ../packages/build-tools
      working-directory: ${{ inputs.example_app }}

    - name: 🛠 Add RNRepo to Android gradle
      shell: bash
      run: bun run .github/workflows/scripts/applyRNRepo.ts ${INPUTS_EXAMPLE_APP}/android ${INPUTS_EXAMPLE_APP}/ios
      env:
        INPUTS_EXAMPLE_APP: ${{ inputs.example_app }}

    - name: 🔧 Set RNRepo Env Variable
      if: ${{ inputs.disable_rnrepo == 'true' }}
      shell: bash
      run: echo "DISABLE_RNREPO=${INPUTS_DISABLE_RNREPO}" >> $GITHUB_ENV
      env:
        INPUTS_DISABLE_RNREPO: ${{ inputs.disable_rnrepo }}
