name: ✨ Feature Request
description: Propose a new feature for RNRepo
title: "[FEATURE] "
labels: ["feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: 📝 Feature Description
      description: Explain what new feature should be added to RNRepo
      placeholder: |
        - Describe the feature here...
        - What problem does it solve?
        - Are there any workarounds currently?
        - How could it works?
    validations:
      required: true
