name: Setup Expo Example App
description: Creates an Expo app, installs dependencies, and adds @rnrepo/expo-config-plugin

inputs:
  example_app:
    description: 'Name of the Expo app directory to create'
    required: true
  expo_sdk_major_version:
    description: 'Expo SDK major version used in `create-expo-app@latest --template default@sdk-<major_version>`'
    required: false
    default: '55'
  disable_rnrepo:
    description: 'Disable rnrepo config plugin'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: ♻️ Cache bun packages
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~/.bun/install/cache
        key: bun-${{ runner.os }}-${{ inputs.expo_sdk_major_version }}-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          bun-${{ runner.os }}-${{ inputs.expo_sdk_major_version }}-
          bun-${{ runner.os }}-

    - name: 🏗 Setup Bun
      uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1.2.2
      with:
        bun-version: latest

    - name: 📦 Install dependencies
      shell: bash
      run: bun install --ignore-scripts

    - name: 🏗 Create Expo App
      shell: bash
      run: bunx create-expo-app@latest ${INPUTS_EXAMPLE_APP} --no-install --template "default@sdk-${INPUTS_EXPO_SDK_MAJOR_VERSION}"
      env:
        INPUTS_EXAMPLE_APP: ${{ inputs.example_app }}
        INPUTS_EXPO_SDK_MAJOR_VERSION: ${{ inputs.expo_sdk_major_version }}

    - name: 📦 Install app dependencies
      shell: bash
      run: bun install --ignore-scripts
      working-directory: ${{ inputs.example_app }}

      # runs npm due to `error: @rnrepo/build-tools@<not-existing-version> failed to resolve`
      # testing before release after the version bump was impossible
    - name: 📦 Install @rnrepo/build-tools and @rnrepo/expo-config-plugin
      shell: bash
      run: npm install ../packages/build-tools ../packages/expo-config-plugin
      working-directory: ${{ inputs.example_app }}

    - name: 🔧 Add plugin to app.json
      shell: bash
      run: jq '.expo.plugins |= (. + ["@rnrepo/expo-config-plugin"] | unique)' app.json > app.json.tmp && mv app.json.tmp app.json
      working-directory: ${{ inputs.example_app }}

    - name: 🔧 Set RNRepo Env Variable
      if: ${{ inputs.disable_rnrepo == 'true' }}
      shell: bash
      run: echo "DISABLE_RNREPO=${INPUTS_DISABLE_RNREPO}" >> $GITHUB_ENV
      env:
        INPUTS_DISABLE_RNREPO: ${{ inputs.disable_rnrepo }}
