/*
 * This source file was generated by the Gradle 'init' task
 */
package org.buildle
import org.gradle.api.Plugin
import org.gradle.api.initialization.Settings
import groovy.json.JsonSlurper
import groovy.json.JsonBuilder
import java.nio.file.Files
import java.nio.file.Paths

class PreventRNLinkPlugin implements Plugin<Settings> {
    void apply(Settings settings) {
        settings.gradle.settingsEvaluated {
            // Maven dependency mappings
            def mavenDependencies = [
                'react-native-device-info': 'com:ReactNativeDeviceInfo:1.0.0',
                'react-native-video': 'com:ReactNativeVideo:1.0.0',
                'react-native-svg': 'com.swmansion:ReactNativeSvg:1.0.0',
                'react-native-screens': 'com.swmansion:ReactNativeScreens:1.0.0',
                'react-native-linear-gradient': 'com.BV:LinearGradient:1.0.0',
                'react-native-sqlite-storage': 'com:ReactNativeSqliteStorage:1.0.0'
            ]

            // Convert Maven dependency keys to Gradle project paths
            List<String> excludedProjectsPaths = mavenDependencies.keySet().collect { ":$it" }

            excludedProjectsPaths.each { excludedProjectPath ->
                File unusedDirectory = new File(settings.rootDir, "build/unused/${excludedProjectPath.replace(':', '')}")
                if (!unusedDirectory.exists()) {
                    unusedDirectory.mkdirs()
                    println "Created unused directory for $excludedProjectPath at: ${unusedDirectory.path}"
                }
                
                if (settings.findProject(excludedProjectPath)) {
                    settings.project(excludedProjectPath).projectDir = unusedDirectory
                    println "🚫 Excluded $excludedProjectPath by setting project dir to an unused directory."
                } else {
                    println "❌ Project $excludedProjectPath not found."
                }
            }

            def autolinkingFile = new File(settings.rootProject.projectDir, "build/generated/autolinking/autolinking.json")
            if (autolinkingFile.exists()) {
                def slurper = new JsonSlurper()
                def json = slurper.parse(autolinkingFile) as Map
                def dependencies = json.get('dependencies') as Map<String, Map>
                
                dependencies.each { key, value ->
                    def mavenDependency = mavenDependencies.get(key)
                    if (mavenDependency) {
                        def platformsMap = value.get('platforms')
                        if (platformsMap && platformsMap.containsKey('android')) {
                            def androidMap = platformsMap.get('android')
                            androidMap.put('sourceDir', '')
                            androidMap.put('mavenDependency', mavenDependency)
                            androidMap.put('componentDescriptors', [])
                            platformsMap.put('android', androidMap)
                        }
                    } else {
                        value.put('mavenDependency', null)
                    }
                }

                def builder = new JsonBuilder(json)
                autolinkingFile.text = builder.toPrettyString()
                println "Updated autolinking.json successfully."
            } else {
                println "The specified autolinking.json file does not exist: ${autolinkingFile.path}"
            }
        }
    }
}