/*
 * This source file was generated by the Gradle 'init' task
 */
package org.buildle

import org.gradle.api.Plugin
import org.gradle.api.initialization.Settings

class PreventRNLinkPlugin implements Plugin<Settings> {
    void apply(Settings settings) {
        settings.gradle.settingsEvaluated {
            // Output to console to confirm plugin is working
            println "✅ Modifying settings to exclude react-native-device-info..."

            // Defining the project path for react-native-reanimated
            String excludedProjectPath = ':react-native-device-info'

            // Example redirection to a dummy directory
            File unusedDirectory = new File(settings.rootDir, 'build/unused')
            if (!unusedDirectory.exists()) {
                unusedDirectory.mkdirs() // Ensure the directory exists
            }

            println "OK " + settings.project(excludedProjectPath)

            // Check and modify the specific project directory to an unused one
            if (settings.project(excludedProjectPath)) {
                println "first!"
                settings.project(excludedProjectPath).projectDir = unusedDirectory
                println "🚫 Excluded ${excludedProjectPath} by setting project dir to an unused directory."
            }
        }
    }
}
