name: Lint, Test and Validate

run-name: Lint, test sources and validate json

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-validate:
    runs-on: rnrepo-ubuntu-latest
    timeout-minutes: 60
    permissions:
      actions: read
      contents: read
      pull-requests: read
    outputs:
      typescript: ${{ steps.filter.outputs.typescript }}
      kotlin: ${{ steps.filter.outputs.kotlin }}
      json: ${{ steps.filter.outputs.json }}
    concurrency:
      group: lint-and-validate-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: 🔍 Check for file changes
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: filter
        with:
          filters: |
            typescript:
              - '**/*.ts'
              - '**/*.tsx'
              - '.github/workflows/lint-and-validate.yml'
            kotlin:
              - 'packages/build-tools/gradle-plugin/**'
              - '.github/workflows/lint-and-validate.yml'
            json:
              - '*.json'
              - '.github/workflows/lint-and-validate.yml'

      - name: 🏗 Setup Bun
        uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1.2.2
        with:
          bun-version: latest

      - name: 🗃️ Cache Bun and Gradle
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ~/.bun/install/cache
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-bun-gradle-${{ hashFiles('**/bun.lock', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-bun-gradle-

      - name: 📦 Install dependencies
        run: bun install --ignore-scripts

      - name: 🔍 Lint kotlin
        if: ${{ steps.filter.outputs.kotlin == 'true' }}
        run: bun run lint-gradle-client

      - name: 🔍 Lint typescript
        if: ${{ steps.filter.outputs.typescript == 'true' }}
        run: bun run lint-ts

      - name: ✅ Validate JSON files
        if: ${{ steps.filter.outputs.json == 'true' }}
        run: bun run validate

      - name: 🧪 Run gradle-client tests
        if: ${{ steps.filter.outputs.kotlin == 'true' }}
        run: bun run test-gradle-client

      - name: 🧪 Run ts tests
        if: ${{ steps.filter.outputs.typescript == 'true' }}
        run: bun test
