name: Publish Expo Config Plugin to npm

run-name: Publish @rnrepo/expo-config-plugin to npm

on:
  workflow_dispatch:
    inputs:
      beta_or_latest:
        description: 'Publish as beta or latest'
        required: true
        default: 'beta'
        type: choice
        options:
          - 'beta'
          - 'latest'

jobs:
  publish-expo-config-plugin:
    runs-on: rnrepo-ubuntu-latest
    timeout-minutes: 30
    permissions:
      id-token: write  # Required for OIDC
      contents: read
    env:
      PLUGIN_DIR: packages/expo-config-plugin
    defaults:
      run:
        working-directory: ${{ env.PLUGIN_DIR }}

    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: 🏗 Setup Bun
        uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1.2.2
        with:
          bun-version: latest

      - name: 🏗 Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: 🏗 Update npm
        # Ensure npm 11.5.1 or later is installed
        run: npm install -g npm@latest

      - name: 📦 Install dependencies
        run: bun install --ignore-scripts

      - name: 🔨 Build plugin
        run: bun run build

      - name: 🚀 Publish to npm
        run: npm publish --tag ${GITHUB_EVENT_INPUTS_BETA_OR_LATEST}
        env:
          CI: true  # Runs tests without watcher
          GITHUB_EVENT_INPUTS_BETA_OR_LATEST: ${{ github.event.inputs.beta_or_latest }}
